### ISSUE TITLE
/n flag not working

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#17]
The /n flag is used in events that display text entered by the designer. This requires the player to press <ENTER> before continuing. Currently it shows as "/n" in the text and does not require the player to anything.

**Comment by grannypron** [comment]
Have you seen this happening in SAs or other locations as well?  Is there anywhere that this works properly compared to where it doesn't?  If there is nowhere that it does work, I'm wondering if we can try \n instead of /n.  If it works in some places but not others, then it is probably a bug and I can compare relevant code pieces.,

**Comment by manikus** [comment]
This flag is only used in events in the text that will display to the player. I have tried it in Text Statement Events and it does not work.
Actually, I'm not sure that this should even be all events, only those that give a message (as opposed to a menu).  we can discuss this further if we need to.

**Comment by grannypron** [comment]
Roger.  I am just trying to figure out if this is something that was implemented but is now broken or if this is something that was not ever implemented.  I'm thinking no one has ever put the code in to make this work.  Could you try \n and see if that works?

**Comment by manikus** [comment]
Yes, it was implemented. I recall going back and forth with Paul, because it was addig a blank line as well, but I'll be damned if I can find the email.

**Comment by grannypron** [comment]
Yep I can see it in there.  It is thoroughly commented out like the /h flag was.   It looks to me like some refactoring occurred where FormatPausedText(), FormatJournalText(), and FormatDisplayText() were all changed to leverage a single method FormatMultiLineText().  Unfortunately, some of the functionality that was in these functions were not quite ported over (possibly because they did not apply to all) to FormatDisplayText(). Any changes to FormatDisplayText() will probably affect all these other areas of the game, too, which may warrant a greater testing scope.  It's going to be kinda tricky to work this in because FormatDisplayText() does not get a reference to the larger scope of what is going on in the game (which would allow it to use fields / methods that would pause), but we will see what we can see.

**Comment by manikus** [comment]
Finally found where we talked about /n flag. It looks like Paul implemented this feature with version 3.08 . See the thread for details. http://ua.reonis.com/index.php?topic=3602.msg51766#msg51766

**Comment by grannypron** [comment]
[DungeonCraftEditor_5.26_uaf_00017.zip](https://github.com/grannypron/uaf/files/5647370/DungeonCraftEditor_5.26_uaf_00017.zip)

Here's an initial implementation. Lmk what you think.

**Comment by grannypron** [comment]
"Downloaded it and gave it a try. :)
The /n flag does cause the engine to force the player to press <ENTER> to continue, exactly as we hoped. I noticed that a blank line was inserted at the start of the next text box. But, other than that, worked like I hoped it would."

"Yeah the logic for waiting for the enter key seemed to be tied to a particular line of text.  I didn't want to tease that connection out too much for fear of breaking something else.  If you like I can add another ticket for supporting enter key pause prompts without breaking the text line.  Meanwhile I am going to close #17 and roll this into the master branch unless anyone voices objection."

http://ua.reonis.com/index.php?topic=3967.msg58195#msg58195

Closing.
