### ISSUE TITLE
Request: Cyrillic support

### ISSUE THREAD

**Issue by Reotor** [grannypron/uaf#41]
Can you please add Cyrillic support to the Dungeon Craft? The program cannot work with Russian text at the moment. In the editor itself, the Russian text is visible, but in the game, instead of the Russian text, only an empty space. Unfortunately, I do not understand anything about this (unicode, cp866 or what is needed for this).  I beg you to do this, the Russian-speaking community will be very grateful to you!

**Comment by grannypron** [comment]
Copying / pasting cyrillic text into the editor textboxes results in "?" characters.   First step would be to modify those controls somehow to let people paste those characters into the textbox.  Then, make sure that the data is saved appropriately.  That would allow developers to get the text in there while any remaining work is done on displaying the characters in the game.  This will probably be a decent amount of work.

**Comment by Reotor** [comment]
> Copying / pasting cyrillic text into the editor textboxes results in "?" characters. First step would be to modify those controls somehow to let people paste those characters into the textbox. Then, make sure that the data is saved appropriately. That would allow developers to get the text in there while any remaining work is done on displaying the characters in the game. This will probably be a decent amount of work.

Russian text when inserted into the text fields of the editor is displayed normally, but in the game that is obtained after creation, instead of the Russian text, there is just an empty space

**Comment by grannypron** [comment]
That is super weird because when I copy/paste text from https://r12a.github.io/scripts/cyrillic/ I get ?s in that same field that you screenshotted.    That is good news, though.  Less work to do.  Maybe I need a Cyrillic keyboard or something.  Never worked with it before,

**Comment by Reotor** [comment]
Thank you very much! If I can do something to help in solving this problem, I will gladly do it.

**Comment by grannypron** [comment]
Could you attach or post a dsn to the forums?  That way I won't have to struggle with setting my locale and whatnot to get the text in there.

**Comment by Reotor** [comment]
I think so, but what is dsn?

**Comment by grannypron** [comment]
Your .dsn directory with the build of your game.  I should start a gitter for this.

**Comment by grannypron** [comment]
Here we go: https://gitter.im/uaf-gitter/community

**Comment by Reotor** [comment]
> Here we go: https://gitter.im/uaf-gitter/community

I followed your link and wrote to you there

**Comment by grannypron** [comment]
There are a couple of places that are stripping out non-ASCII characters that would have to be changed.   These include, but are not limited to: 

FormattedText.cpp - StripInvalidChars()
CDXBitmapFont.cpp - MAX_CHAR enum
Possibly the assertion in CDXBitmapFont::GetTextWidth() that ASSERT( (ch >= 0) && (ch <= MAX_CHAR-1) );

Also, CDXBitmapFontArray will have to be populated to have these symbols in CDXBitmapFont::Create() (note that 128 is hardcoded in the for loop as well)

What concerns me more is that when we walk through the strings and converting them to integers for checking, we get values that are very high or are < 0, which is probably because the byte values are being read as 2s complement or something like that.

**Comment by grannypron** [comment]
To press further into the string byte stuff, the two characters гч are read in as 4 bytes - -48, -77 and -47, -121.   In a hex editor, the values of these characters in the .lvl file is D0, B3 and D1, 87 or 208, 179  and 209, 135

**Comment by grannypron** [comment]
So these characters are then encoded into the file as UTF symbols.  https://en.wikipedia.org/wiki/Ge_(Cyrillic)#Computing_codes documents how г is represented as 208,179.

**Comment by grannypron** [comment]
Important wrinkle:  Text strings are stored using the character set that they are entered/imported with.  For example, in the OP's level design .lvl (binary) file we see EF F0, which does NOT correspond with any UTF-8 encoding character.  In an export txt file this screen displays П (not sure about case), but someone that is opening that file with the default Latin charset will see ïð.

This means that we are probably going to need to use a config.txt file flag to set the character set when we call CreateFont().  Default probably being the ASCII charset.

**Comment by grannypron** [comment]
So, my file with гч above was saved as UTF-8 & Unicode from notepad.  This is probably NOT how we want to approach things just yet because that is not how the exports save/load now.  For a first approach, I will continue to encode the files with the default character set (in my case, Latin) but just allow characters outside of ASCII to be allowed to be drawn.  ï, for example.  If we specify the right character set in CreateFont() then this may render just fine as the text is entered.

**Comment by grannypron** [comment]
When stepping through the bytes of these characters, they are negative because they are 8 bits using 2's complement.  So, EF is -17 is actually 239.  To get the unsigned value, just &255.  So, if support these characters, we would change all the CDXBitmapFont::Draw* methods to handle negative values by reading two bytes and then turning the negative value into its 2's complement and left shift it and add the 2's complement of the second bit.   This would, presumably give us the index to use in CDXBitmapFontArray.   Also, that array will have to grow from a length of 128 to 65,536.  And we will have to figure out how to load all of those glyphs in the PaintCharactersInSurface() method - and the surface that is used to hold those glyphs will also increase.

**Comment by grannypron** [comment]
My mistake, in OPs level.txt the characters are represented with 8-bit, not 16.  So EF F0 is 2 characters, not one.   When I try to paste those characters into my notepad and save as UTF-8, however, then my Unicode characters are using 16 bits.

**Comment by grannypron** [comment]
By changing the char types to unsigned right before printing, they can represent the 255 bytes in the codepage.  The graphics libraries do not seem to have trouble displaying characters over 128 and I have a build that successfulyy displays ï (and other characters, I presume).  Attaching.   Remains to be seen what it will display when the OS's locale set to a different character set like CP-1251.  Sending to the OP to try it out.

[DungeonCraft_5.27_uaf_00041.zip](https://github.com/grannypron/uaf/files/5850814/DungeonCraft_5.27_uaf_00041.zip)

**Comment by Reotor** [comment]
YES! It works!!! But partially.  But partially. It feels like not all the text fits in width, I will now try to show it in the screenshot:
![Screenshot_1](https://user-images.githubusercontent.com/77742895/105386807-e7f3ec00-5c25-11eb-9dc5-1c8ed3c4d17e.jpg)
Apparently, the text is shifted to the left for some reason

**Comment by Reotor** [comment]
These letters are missing:

![Screenshot_3](https://user-images.githubusercontent.com/77742895/105387088-4325de80-5c26-11eb-8c37-01076e8351f7.jpg)

**Comment by grannypron** [comment]
Problem was related to FormatMultiLineText and FORMATTED_TEXT::Backup().  Backup was traversing over the string character by character and looking for characters "less than" the space character.  Since these were signed chars, the ones over 128 were being skipped over, thereby losing that word in the backup.

[DungeonCraft_5.27_uaf_00041b.zip](https://github.com/grannypron/uaf/files/5851478/DungeonCraft_5.27_uaf_00041b.zip)

**Comment by grannypron** [comment]
This build includes CHARSET config.txt option.

[DungeonCraft_5.27_uaf_00041c.zip](https://github.com/grannypron/uaf/files/5852060/DungeonCraft_5.27_uaf_00041c.zip)

**Comment by grannypron** [comment]
The CHARSET config option should use one of the values from this list from Microsoft converted into an integer.

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wmf/0d0b32ac-a836-4bd2-a112-b6000a1b4fc9

   ANSI_CHARSET = 0x00000000,
   DEFAULT_CHARSET = 0x00000001,
   SYMBOL_CHARSET = 0x00000002,
   MAC_CHARSET = 0x0000004D,
   SHIFTJIS_CHARSET = 0x00000080,
   HANGUL_CHARSET = 0x00000081,
   JOHAB_CHARSET = 0x00000082,
   GB2312_CHARSET = 0x00000086,
   CHINESEBIG5_CHARSET = 0x00000088,
   GREEK_CHARSET = 0x000000A1,
   TURKISH_CHARSET = 0x000000A2,
   VIETNAMESE_CHARSET = 0x000000A3,
   HEBREW_CHARSET = 0x000000B1,
   ARABIC_CHARSET = 0x000000B2,
   BALTIC_CHARSET = 0x000000BA,
   RUSSIAN_CHARSET = 0x000000CC,
   THAI_CHARSET = 0x000000DE,
   EASTEUROPE_CHARSET = 0x000000EE,
   OEM_CHARSET = 0x000000FF

**Comment by grannypron** [comment]
Commit is f053d9c

**Comment by grannypron** [comment]
NOTE:  Turns out that setting the config flag doesn't do much.  The call to Font.CreateFont() is probably overridden by Windows locale settings.  Still this might not be true in all Windows versions and so it is probably still a good idea to specify the flag to the expected locale anyway.

This does mean, however, that games that are made in one locale and played in a different locale won't show up the same.
