### ISSUE TITLE
DungeonCraftEditor- importing spells database not reading correctly

### ISSUE THREAD

**Issue by manikus** [grannypron/uaf#69]
When importing the spells databse (default one in TemplateDesign.dsn), the editor is reading "Pyrotechnics|Ranger Magic User" as "Pyrotechnics|Ranger" which is a duplicate name. I use the pipe with words with spaces in multiple databases. This had not been an issue with previous releases.

**Comment by grannypron** [comment]
This seemed to work for me using the latest snapshot and the spells file from 

https://github.com/manikus/default_databases_for_Dungeon_Craft/blob/main/spells.txt

Maybe it was fixed with the fix for #68 ?

![image](https://user-images.githubusercontent.com/19980049/227644635-aef873af-a86d-4668-9a27-0faf5365566d.png)

Could you confirm that it is working now?

**Comment by manikus** [comment]
I don't know what I could have done to make this work, but I do confirm it worked just fine when importing. Thank you.
